import { NextPage } from 'next';
import Head from 'next/head';
import Router from 'next/router';
import NProgress from 'nprogress'; //nprogress module
import React, { ReactElement, ReactNode } from 'react';

import { Layouts } from 'app';
import type { AppProps } from 'next/app';

import 'nprogress/nprogress.css';
// eslint-disable-next-line import/no-internal-modules
import '../public/globals.scss';

Router.events.on('routeChangeStart', () => NProgress.start());
Router.events.on('routeChangeComplete', () => NProgress.done());
Router.events.on('routeChangeError', () => NProgress.done());

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts withLayout={!Component.getLayout}>{getLayout(<Component {...pageProps} />)}</Layouts>
    </>
  );
}

export default MyApp;
